services:
  app:
    image: app
    build:
      context: .
      dockerfile: Dockerfile
      no_cache: true
    ports:
      - 5000:5000
      - 5432:5432
    deploy:
      restart_policy:
        condition: unless-stopped
