#!/bin/bash

NAME=solarin_backend
DIR=/home/app/PPDB-Template-App/backend
USER=app
GROUP=app
WORKERS=3
WORKER_CLASS=uvicorn.workers.UvicornWorker
VENV=$DIR/.venv/bin/activate
BIND=unix:$DIR/run/gunicorn.sock
LOG_LEVEL=error

cd $DIR
source $VENV

exec gunicorn src.app.__main__:app \
  --keyfile=./team6.ua-ppdb.me/privkey.pem \
  --certfile=./team6.ua-ppdb.me/fullchain.pem \
  --name $NAME \
  --workers $WORKERS \
  --worker-class $WORKER_CLASS \
  --user=$USER \
  --group=$GROUP \
  --bind=$BIND \
  --log-level=$LOG_LEVEL \
  --log-file=-
