"""

Revision ID: 112a81bb72a7
Revises: 1b78289a1d29
Create Date: 2024-05-15 14:17:57.879658

"""
from typing import Sequence, Union
import src

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '112a81bb72a7'
down_revision: Union[str, None] = '1b78289a1d29'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
