"""

Revision ID: 147ecf6e61cf
Revises: 10935f67d319
Create Date: 2024-03-19 19:05:26.348578

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '147ecf6e61cf'
down_revision: Union[str, None] = '10935f67d319'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('planet_name_key', 'planet', type_='unique')
    op.add_column('producesResources', sa.Column('base_production', sa.Integer(), nullable=False))
    op.add_column('producesResources', sa.Column('max_capacity', sa.Integer(), nullable=False))
    op.drop_column('productionBuildingType', 'base_production')
    op.drop_column('productionBuildingType', 'max_capacity')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('productionBuildingType', sa.Column('max_capacity', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('productionBuildingType', sa.Column('base_production', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('producesResources', 'max_capacity')
    op.drop_column('producesResources', 'base_production')
    op.create_unique_constraint('planet_name_key', 'planet', ['name'])
    # ### end Alembic commands ###
