"""empty message

Revision ID: 58dd3622b374
Revises: 1b78289a1d29
Create Date: 2024-05-13 14:09:23.866166

"""
from typing import Sequence, Union
import src

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '58dd3622b374'
down_revision: Union[str, None] = '1b78289a1d29'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
