"""

Revision ID: 8076ef939a06
Revises: 
Create Date: 2024-03-25 21:31:39.712075

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8076ef939a06'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('buildingType',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('required_rank', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_table('messageBoard',
    sa.Column('bid', sa.Integer(), nullable=False),
    sa.Column('chat_name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('bid')
    )
    op.create_table('planetRegionType',
    sa.Column('region_type', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('region_type')
    )
    op.create_table('planetType',
    sa.Column('type', sa.TEXT(), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('type')
    )
    op.create_table('resourceType',
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_table('spaceRegion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('troopType',
    sa.Column('type', sa.TEXT(), nullable=False),
    sa.Column('training_time', sa.Integer(), nullable=False),
    sa.Column('attack', sa.Integer(), nullable=False),
    sa.Column('defense', sa.Integer(), nullable=False),
    sa.Column('city_attack', sa.Integer(), nullable=False),
    sa.Column('city_defense', sa.Integer(), nullable=False),
    sa.Column('recovery', sa.Integer(), nullable=False),
    sa.Column('speed', sa.Integer(), nullable=False),
    sa.Column('required_rank', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('type')
    )
    op.create_table('CreationCost',
    sa.Column('building_name', sa.String(), nullable=False),
    sa.Column('cost_type', sa.String(), nullable=False),
    sa.Column('cost_amount', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['building_name'], ['buildingType.name'], initially='DEFERRED', deferrable=True),
    sa.ForeignKeyConstraint(['cost_type'], ['resourceType.name'], initially='DEFERRED', deferrable=True),
    sa.PrimaryKeyConstraint('building_name', 'cost_type')
    )
    op.create_table('alliance',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('message_board', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['message_board'], ['messageBoard.bid'], ),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_table('barracksType',
    sa.Column('name', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['name'], ['buildingType.name'], initially='DEFERRED', deferrable=True),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_table('houseType',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('residents', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['name'], ['buildingType.name'], initially='DEFERRED', deferrable=True),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_table('planet',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.TEXT(), nullable=False),
    sa.Column('planet_type', sa.TEXT(), nullable=False),
    sa.Column('space_region_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['planet_type'], ['planetType.type'], ),
    sa.ForeignKeyConstraint(['space_region_id'], ['spaceRegion.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('productionBuildingType',
    sa.Column('name', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['name'], ['buildingType.name'], initially='DEFERRED', deferrable=True),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_table('towerType',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('attack', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['name'], ['buildingType.name'], initially='DEFERRED', deferrable=True),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_table('troopTypeCost',
    sa.Column('troop_type', sa.TEXT(), nullable=False),
    sa.Column('resource_type', sa.TEXT(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['resource_type'], ['resourceType.name'], initially='DEFERRED', deferrable=True),
    sa.ForeignKeyConstraint(['troop_type'], ['troopType.type'], initially='DEFERRED', deferrable=True),
    sa.PrimaryKeyConstraint('troop_type', 'resource_type')
    )
    op.create_table('wallType',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('defense', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['name'], ['buildingType.name'], initially='DEFERRED', deferrable=True),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_table('planetRegion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('planet_id', sa.Integer(), nullable=True),
    sa.Column('region_type', sa.TEXT(), nullable=False),
    sa.ForeignKeyConstraint(['planet_id'], ['planet.id'], ),
    sa.ForeignKeyConstraint(['region_type'], ['planetRegionType.region_type'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('producesResources',
    sa.Column('building_name', sa.String(), nullable=False),
    sa.Column('resource_name', sa.String(), nullable=False),
    sa.Column('base_production', sa.Integer(), nullable=False),
    sa.Column('max_capacity', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['building_name'], ['productionBuildingType.name'], initially='DEFERRED', deferrable=True),
    sa.ForeignKeyConstraint(['resource_name'], ['resourceType.name'], initially='DEFERRED', deferrable=True),
    sa.PrimaryKeyConstraint('building_name', 'resource_name')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('hashed_password', sa.String(), nullable=True),
    sa.Column('alliance', sa.String(), nullable=True),
    sa.Column('faction_name', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['alliance'], ['alliance.name'], initially='DEFERRED', deferrable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_index(op.f('ix_user_id'), 'user', ['id'], unique=False)
    op.create_table('FriendRequest',
    sa.Column('from_user_id', sa.Integer(), nullable=False),
    sa.Column('to_user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['from_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['to_user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('from_user_id', 'to_user_id')
    )
    op.create_table('allianceRequest',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('alliance_name', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['alliance_name'], ['alliance.name'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('army',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('last_update', sa.TIME(), nullable=True),
    sa.Column('x', sa.Float(precision=53), nullable=False),
    sa.Column('y', sa.Float(precision=53), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('city',
    sa.Column('region_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('controlled_by', sa.Integer(), nullable=False),
    sa.Column('x', sa.Float(precision=53), nullable=False),
    sa.Column('y', sa.Float(precision=53), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['controlled_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['region_id'], ['planetRegion.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('friendsOf',
    sa.Column('user1_id', sa.Integer(), nullable=False),
    sa.Column('user2_id', sa.Integer(), nullable=False),
    sa.Column('message_board', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['message_board'], ['messageBoard.bid'], ),
    sa.ForeignKeyConstraint(['user1_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['user2_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user1_id', 'user2_id')
    )
    op.create_table('hasResources',
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('resource_type', sa.String(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['resource_type'], ['resourceType.name'], ),
    sa.PrimaryKeyConstraint('owner_id', 'resource_type')
    )
    op.create_table('message',
    sa.Column('mid', sa.Integer(), nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=False),
    sa.Column('message_board', sa.Integer(), nullable=False),
    sa.Column('create_date_time', sa.TIMESTAMP(), nullable=False),
    sa.Column('parent_message_id', sa.Integer(), nullable=True),
    sa.Column('body', sa.TEXT(), nullable=False),
    sa.ForeignKeyConstraint(['message_board'], ['messageBoard.bid'], ),
    sa.ForeignKeyConstraint(['parent_message_id'], ['message.mid'], initially='DEFERRED', deferrable=True),
    sa.ForeignKeyConstraint(['sender_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('mid')
    )
    op.create_table('armyConsistsOf',
    sa.Column('army_id', sa.Integer(), nullable=False),
    sa.Column('troop_type', sa.String(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['army_id'], ['army.id'], initially='DEFERRED', deferrable=True),
    sa.ForeignKeyConstraint(['troop_type'], ['troopType.type'], initially='DEFERRED', deferrable=True),
    sa.PrimaryKeyConstraint('army_id', 'troop_type', 'rank')
    )
    op.create_table('buildingInstance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('city_id', sa.Integer(), nullable=False),
    sa.Column('building_type', sa.String(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['building_type'], ['buildingType.name'], initially='DEFERRED', deferrable=True),
    sa.ForeignKeyConstraint(['city_id'], ['city.id'], initially='DEFERRED', deferrable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_buildingInstance_id'), 'buildingInstance', ['id'], unique=False)
    op.create_table('trainingQueue',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('building_id', sa.Integer(), nullable=False),
    sa.Column('army_id', sa.Integer(), nullable=False),
    sa.Column('train_remaining', sa.Integer(), nullable=True),
    sa.Column('troop_type', sa.String(), nullable=True),
    sa.Column('rank', sa.Integer(), nullable=True),
    sa.Column('training_size', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['army_id'], ['army.id'], initially='DEFERRED', deferrable=True),
    sa.ForeignKeyConstraint(['building_id'], ['buildingInstance.id'], initially='DEFERRED', deferrable=True),
    sa.ForeignKeyConstraint(['troop_type'], ['troopType.type'], initially='DEFERRED', deferrable=True),
    sa.PrimaryKeyConstraint('id', 'building_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('trainingQueue')
    op.drop_index(op.f('ix_buildingInstance_id'), table_name='buildingInstance')
    op.drop_table('buildingInstance')
    op.drop_table('armyConsistsOf')
    op.drop_table('message')
    op.drop_table('hasResources')
    op.drop_table('friendsOf')
    op.drop_table('city')
    op.drop_table('army')
    op.drop_table('allianceRequest')
    op.drop_table('FriendRequest')
    op.drop_index(op.f('ix_user_id'), table_name='user')
    op.drop_table('user')
    op.drop_table('producesResources')
    op.drop_table('planetRegion')
    op.drop_table('wallType')
    op.drop_table('troopTypeCost')
    op.drop_table('towerType')
    op.drop_table('productionBuildingType')
    op.drop_table('planet')
    op.drop_table('houseType')
    op.drop_table('barracksType')
    op.drop_table('alliance')
    op.drop_table('CreationCost')
    op.drop_table('troopType')
    op.drop_table('spaceRegion')
    op.drop_table('resourceType')
    op.drop_table('planetType')
    op.drop_table('planetRegionType')
    op.drop_table('messageBoard')
    op.drop_table('buildingType')
    # ### end Alembic commands ###
