"""

Revision ID: 9bb6400d00ad
Revises: 9d5f6ad5a5f3
Create Date: 2024-03-18 17:23:28.073843

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9bb6400d00ad'
down_revision: Union[str, None] = '9d5f6ad5a5f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hasResources',
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('resource_type', sa.String(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['resource_type'], ['resourceType.name'], ),
    sa.PrimaryKeyConstraint('owner_id', 'resource_type')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('hasResources')
    # ### end Alembic commands ###
