"""empty message

Revision ID: 9c0e018b231f
Revises: 715a52e9823a
Create Date: 2024-05-19 11:50:33.811942

"""
from typing import Sequence, Union
import src

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9c0e018b231f'
down_revision: Union[str, None] = '715a52e9823a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
