"""empty message

Revision ID: a132d85ff70a
Revises: 9d5f6ad5a5f3
Create Date: 2024-03-17 11:40:08.627237

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a132d85ff70a'
down_revision: Union[str, None] = '9d5f6ad5a5f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('army', sa.Column('x', sa.Float(precision=53), nullable=False))
    op.add_column('army', sa.Column('y', sa.Float(precision=53), nullable=False))
    op.add_column('city', sa.Column('x', sa.Float(precision=53), nullable=False))
    op.add_column('city', sa.Column('y', sa.Float(precision=53), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('city', 'y')
    op.drop_column('city', 'x')
    op.drop_column('army', 'y')
    op.drop_column('army', 'x')
    # ### end Alembic commands ###
