name: Backend Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      # Label used to access the service container
      postgres:
        # Docker Hub image
        image: postgres
        # Provide the password for postgres
        env:
          POSTGRES_PASSWORD: postgres
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          # Maps tcp port 5432 on service container to the host
          - 5432:5432

    steps:


      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: 3.10.12
      - uses: snok/install-poetry@v1
        with:
          version: 1.7.0
      - run: poetry install --no-interaction --no-root
        working-directory: ./backend
      - run: poetry run pytest
        working-directory: ./backend
